import Modal from "@/Components/Modal";
import "./globals.css";

export const metadata = {
  title: "Trello 2.0 clone",
  description: "Generated by Sayan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#FB]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
